### PR TITLE
Display a message no reminders

### LINKED ISSUE #5: Display a message if there are no reminders
Update the app to have a conditional that will only display a reminder if reminders exist. In other words, if there are existing reminders the user should see the most recent reminder. If there are no reminders, the user should see a message to add a new note, with a link or button that routes them to `/reminders/new`.

### PR DESCRIPTION
**Pull request by hmorri32**
## Purpose

Alter reminders.hbs to conditionally render a message to create a reminder if no reminders are found

## Approach

use ember if else syntax to conditionally render an H2 tag

### Learning

ember docs on if else syntax

### Follow-up tasks

- [Issue #6 (Example)](https://github.com/flexyford/pull-request/issues)

### Screenshots
cool screenshot

closes #5

### CODE REVIEW

**Comment by hmorri32** [comment]
@martensonbj @Tman22

**Review by martensonbj — CHANGES_REQUESTED** [review]
Is there a test for this?

**Comment by hmorri32** [comment]
@martensonbj @Tman22 there is now an acceptance test for this issue.

**Comment by martensonbj** [comment]
👍

**Pull request merged**
